spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/datajpatest
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc.batch_size: 10
        order_inserts: true
        id.new_generator_mappings: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
